[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "netaddr/version.py"
write_to_template = "__version__ = \"{version}\"\n"
